//AUTO-GENERATED FILE, EDIT AT YOUR OWN RISK
#pragma once
#include <Resource.h>
struct RawResources {static const unsigned char fonts_Roboto_Bold_ttf[];
static const unsigned fonts_Roboto_Bold_ttf_size;
static const unsigned char fonts_Roboto_BoldItalic_ttf[];
static const unsigned fonts_Roboto_BoldItalic_ttf_size;
static const unsigned char fonts_Roboto_Italic_ttf[];
static const unsigned fonts_Roboto_Italic_ttf_size;
static const unsigned char fonts_Roboto_Light_ttf[];
static const unsigned fonts_Roboto_Light_ttf_size;
static const unsigned char fonts_Roboto_Regular_ttf[];
static const unsigned fonts_Roboto_Regular_ttf_size;
static const unsigned char fonts_consola_ttf[];
static const unsigned fonts_consola_ttf_size;
static const unsigned char shaders_basic_vert[];
static const unsigned shaders_basic_vert_size;
static const unsigned char shaders_basic_lit_frag[];
static const unsigned shaders_basic_lit_frag_size;
static const unsigned char shaders_basic_unlit_frag[];
static const unsigned shaders_basic_unlit_frag_size;
static const unsigned char sounds_sci_fi_ogg[];
static const unsigned sounds_sci_fi_ogg_size;
static const unsigned char sounds_slow_motion_ogg[];
static const unsigned sounds_slow_motion_ogg_size;
static const unsigned char sounds_test_ogg[];
static const unsigned sounds_test_ogg_size;
static const unsigned char textures_Alien_png[];
static const unsigned textures_Alien_png_size;
static const unsigned char textures_AnimationTest_png[];
static const unsigned textures_AnimationTest_png_size;
static const unsigned char textures_Enemy_png[];
static const unsigned textures_Enemy_png_size;
static const unsigned char textures_Enemy_xcf[];
static const unsigned textures_Enemy_xcf_size;
static const unsigned char textures_Player_png[];
static const unsigned textures_Player_png_size;
static const unsigned char textures_Player_xcf[];
static const unsigned textures_Player_xcf_size;
static const unsigned char textures_PlayerLit_png[];
static const unsigned textures_PlayerLit_png_size;
static const unsigned char textures_asterisk_png[];
static const unsigned textures_asterisk_png_size;
static const unsigned char textures_box_png[];
static const unsigned textures_box_png_size;
static const unsigned char textures_floor_png[];
static const unsigned textures_floor_png_size;
static const unsigned char textures_grid_png[];
static const unsigned textures_grid_png_size;
static const unsigned char textures_scheme_PNG[];
static const unsigned textures_scheme_PNG_size;
static const unsigned char textures_sprites_lpc_female_bracers_png[];
static const unsigned textures_sprites_lpc_female_bracers_png_size;
static const unsigned char textures_sprites_lpc_female_chainmail_png[];
static const unsigned textures_sprites_lpc_female_chainmail_png_size;
static const unsigned char textures_sprites_lpc_female_hurt_png[];
static const unsigned textures_sprites_lpc_female_hurt_png_size;
static const unsigned char textures_sprites_lpc_female_shoulders_png[];
static const unsigned textures_sprites_lpc_female_shoulders_png_size;
static const unsigned char textures_sprites_lpc_female_slash_png[];
static const unsigned textures_sprites_lpc_female_slash_png_size;
static const unsigned char textures_sprites_lpc_female_spellcast_png[];
static const unsigned textures_sprites_lpc_female_spellcast_png_size;
static const unsigned char textures_sprites_lpc_female_walkcycle_png[];
static const unsigned textures_sprites_lpc_female_walkcycle_png_size;
static const unsigned char textures_sprites_lpc_hairfemale_png[];
static const unsigned textures_sprites_lpc_hairfemale_png_size;
static const unsigned char textures_sprites_lpc_hairfemale_xcf[];
static const unsigned textures_sprites_lpc_hairfemale_xcf_size;
static const unsigned char textures_sprites_lpc_hairmale_png[];
static const unsigned textures_sprites_lpc_hairmale_png_size;
static const unsigned char textures_sprites_lpc_hairmale_xcf[];
static const unsigned textures_sprites_lpc_hairmale_xcf_size;
static const unsigned char textures_sprites_lpc_male_hurt_png[];
static const unsigned textures_sprites_lpc_male_hurt_png_size;
static const unsigned char textures_sprites_lpc_male_hurt_pants_png[];
static const unsigned textures_sprites_lpc_male_hurt_pants_png_size;
static const unsigned char textures_sprites_lpc_male_pants_png[];
static const unsigned textures_sprites_lpc_male_pants_png_size;
static const unsigned char textures_sprites_lpc_male_slash_png[];
static const unsigned textures_sprites_lpc_male_slash_png_size;
static const unsigned char textures_sprites_lpc_male_slash_pants_png[];
static const unsigned textures_sprites_lpc_male_slash_pants_png_size;
static const unsigned char textures_sprites_lpc_male_spellcast_png[];
static const unsigned textures_sprites_lpc_male_spellcast_png_size;
static const unsigned char textures_sprites_lpc_male_spellcast_pants_png[];
static const unsigned textures_sprites_lpc_male_spellcast_pants_png_size;
static const unsigned char textures_sprites_lpc_male_walkcycle_png[];
static const unsigned textures_sprites_lpc_male_walkcycle_png_size;
static const unsigned char textures_sprites_lpc_princess_png[];
static const unsigned textures_sprites_lpc_princess_png_size;
static const unsigned char textures_sprites_lpc_princess_xcf[];
static const unsigned textures_sprites_lpc_princess_xcf_size;
static const unsigned char textures_sprites_lpc_soldier_png[];
static const unsigned textures_sprites_lpc_soldier_png_size;
static const unsigned char textures_sprites_lpc_soldier_altcolor_png[];
static const unsigned textures_sprites_lpc_soldier_altcolor_png_size;
static const unsigned char tilemaps_Terrain_tsx[];
static const unsigned tilemaps_Terrain_tsx_size;
static const unsigned char tilemaps_levelOne_json[];
static const unsigned tilemaps_levelOne_json_size;
static const unsigned char tilemaps_terrain_all_png[];
static const unsigned tilemaps_terrain_all_png_size;
static const unsigned char tilemaps_test_json[];
static const unsigned tilemaps_test_json_size;
static const unsigned char tilemaps_testTilemap_json[];
static const unsigned tilemaps_testTilemap_json_size;
static void Init() {
Resources::all.push_back(new Resource("fonts/Roboto-Bold.ttf", fonts_Roboto_Bold_ttf, fonts_Roboto_Bold_ttf_size));
Resources::all.push_back(new Resource("fonts/Roboto-BoldItalic.ttf", fonts_Roboto_BoldItalic_ttf, fonts_Roboto_BoldItalic_ttf_size));
Resources::all.push_back(new Resource("fonts/Roboto-Italic.ttf", fonts_Roboto_Italic_ttf, fonts_Roboto_Italic_ttf_size));
Resources::all.push_back(new Resource("fonts/Roboto-Light.ttf", fonts_Roboto_Light_ttf, fonts_Roboto_Light_ttf_size));
Resources::all.push_back(new Resource("fonts/Roboto-Regular.ttf", fonts_Roboto_Regular_ttf, fonts_Roboto_Regular_ttf_size));
Resources::all.push_back(new Resource("fonts/consola.ttf", fonts_consola_ttf, fonts_consola_ttf_size));
Resources::all.push_back(new Resource("shaders/basic.vert", shaders_basic_vert, shaders_basic_vert_size));
Resources::all.push_back(new Resource("shaders/basic_lit.frag", shaders_basic_lit_frag, shaders_basic_lit_frag_size));
Resources::all.push_back(new Resource("shaders/basic_unlit.frag", shaders_basic_unlit_frag, shaders_basic_unlit_frag_size));
Resources::all.push_back(new Resource("sounds/sci_fi.ogg", sounds_sci_fi_ogg, sounds_sci_fi_ogg_size));
Resources::all.push_back(new Resource("sounds/slow_motion.ogg", sounds_slow_motion_ogg, sounds_slow_motion_ogg_size));
Resources::all.push_back(new Resource("sounds/test.ogg", sounds_test_ogg, sounds_test_ogg_size));
Resources::all.push_back(new Resource("textures/Alien.png", textures_Alien_png, textures_Alien_png_size));
Resources::all.push_back(new Resource("textures/AnimationTest.png", textures_AnimationTest_png, textures_AnimationTest_png_size));
Resources::all.push_back(new Resource("textures/Enemy.png", textures_Enemy_png, textures_Enemy_png_size));
Resources::all.push_back(new Resource("textures/Enemy.xcf", textures_Enemy_xcf, textures_Enemy_xcf_size));
Resources::all.push_back(new Resource("textures/Player.png", textures_Player_png, textures_Player_png_size));
Resources::all.push_back(new Resource("textures/Player.xcf", textures_Player_xcf, textures_Player_xcf_size));
Resources::all.push_back(new Resource("textures/PlayerLit.png", textures_PlayerLit_png, textures_PlayerLit_png_size));
Resources::all.push_back(new Resource("textures/asterisk.png", textures_asterisk_png, textures_asterisk_png_size));
Resources::all.push_back(new Resource("textures/box.png", textures_box_png, textures_box_png_size));
Resources::all.push_back(new Resource("textures/floor.png", textures_floor_png, textures_floor_png_size));
Resources::all.push_back(new Resource("textures/grid.png", textures_grid_png, textures_grid_png_size));
Resources::all.push_back(new Resource("textures/scheme.PNG", textures_scheme_PNG, textures_scheme_PNG_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/female_bracers.png", textures_sprites_lpc_female_bracers_png, textures_sprites_lpc_female_bracers_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/female_chainmail.png", textures_sprites_lpc_female_chainmail_png, textures_sprites_lpc_female_chainmail_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/female_hurt.png", textures_sprites_lpc_female_hurt_png, textures_sprites_lpc_female_hurt_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/female_shoulders.png", textures_sprites_lpc_female_shoulders_png, textures_sprites_lpc_female_shoulders_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/female_slash.png", textures_sprites_lpc_female_slash_png, textures_sprites_lpc_female_slash_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/female_spellcast.png", textures_sprites_lpc_female_spellcast_png, textures_sprites_lpc_female_spellcast_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/female_walkcycle.png", textures_sprites_lpc_female_walkcycle_png, textures_sprites_lpc_female_walkcycle_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/hairfemale.png", textures_sprites_lpc_hairfemale_png, textures_sprites_lpc_hairfemale_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/hairfemale.xcf", textures_sprites_lpc_hairfemale_xcf, textures_sprites_lpc_hairfemale_xcf_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/hairmale.png", textures_sprites_lpc_hairmale_png, textures_sprites_lpc_hairmale_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/hairmale.xcf", textures_sprites_lpc_hairmale_xcf, textures_sprites_lpc_hairmale_xcf_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/male_hurt.png", textures_sprites_lpc_male_hurt_png, textures_sprites_lpc_male_hurt_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/male_hurt_pants.png", textures_sprites_lpc_male_hurt_pants_png, textures_sprites_lpc_male_hurt_pants_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/male_pants.png", textures_sprites_lpc_male_pants_png, textures_sprites_lpc_male_pants_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/male_slash.png", textures_sprites_lpc_male_slash_png, textures_sprites_lpc_male_slash_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/male_slash_pants.png", textures_sprites_lpc_male_slash_pants_png, textures_sprites_lpc_male_slash_pants_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/male_spellcast.png", textures_sprites_lpc_male_spellcast_png, textures_sprites_lpc_male_spellcast_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/male_spellcast_pants.png", textures_sprites_lpc_male_spellcast_pants_png, textures_sprites_lpc_male_spellcast_pants_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/male_walkcycle.png", textures_sprites_lpc_male_walkcycle_png, textures_sprites_lpc_male_walkcycle_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/princess.png", textures_sprites_lpc_princess_png, textures_sprites_lpc_princess_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/princess.xcf", textures_sprites_lpc_princess_xcf, textures_sprites_lpc_princess_xcf_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/soldier.png", textures_sprites_lpc_soldier_png, textures_sprites_lpc_soldier_png_size));
Resources::all.push_back(new Resource("textures/sprites/lpc/soldier_altcolor.png", textures_sprites_lpc_soldier_altcolor_png, textures_sprites_lpc_soldier_altcolor_png_size));
Resources::all.push_back(new Resource("tilemaps/Terrain.tsx", tilemaps_Terrain_tsx, tilemaps_Terrain_tsx_size));
Resources::all.push_back(new Resource("tilemaps/levelOne.json", tilemaps_levelOne_json, tilemaps_levelOne_json_size));
Resources::all.push_back(new Resource("tilemaps/terrain_all.png", tilemaps_terrain_all_png, tilemaps_terrain_all_png_size));
Resources::all.push_back(new Resource("tilemaps/test.json", tilemaps_test_json, tilemaps_test_json_size));
Resources::all.push_back(new Resource("tilemaps/testTilemap.json", tilemaps_testTilemap_json, tilemaps_testTilemap_json_size));
}
};
