# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x86
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug_x86)
  RESCOMP = windres
  TARGETDIR = ../../bin
  TARGET = $(TARGETDIR)/LETC-core.lib
  OBJDIR = obj/x86/Debug/LETC-Core
  DEFINES += -DDEBUG -D_LIB -DFT2_BUILD_LIBRARY -DCRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE
  INCLUDES += -I../../L_ETC-core -I../../Dependencies/GLFW/include -I../../Dependencies/gorilla-audio/include -I../../Dependencies/FreeImage/include -I../../L_ETC-core/ext/freetype/include -I../../L_ETC-core/ext/freetype-gl/include -I../../Dependencies/imgui/include -I../../Dependencies/glad/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -g
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -g -std=c++11
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -lopengl32 -lglfw3 -lFreeImage -lgorilla
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../../Dependencies/gorilla-audio/bin/win32 -L../../Dependencies/FreeImage/lib -L../../Dependencies/GLFW/lib-vc2019 -L../../Dependencies/Freetype/lib -L/usr/lib32 -m32
  LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_x86)
  RESCOMP = windres
  TARGETDIR = ../../bin
  TARGET = $(TARGETDIR)/LETC-core.lib
  OBJDIR = obj/x86/Release/LETC-Core
  DEFINES += -DNDEBUG -DGLEW_STATIC -D_LIB -DFT2_BUILD_LIBRARY -DCRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE
  INCLUDES += -I../../L_ETC-core -I../../Dependencies/GLFW/include -I../../Dependencies/gorilla-audio/include -I../../Dependencies/FreeImage/include -I../../L_ETC-core/ext/freetype/include -I../../L_ETC-core/ext/freetype-gl/include -I../../Dependencies/imgui/include -I../../Dependencies/glad/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O2
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -std=c++11
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += -lopengl32 -lglfw3 -lFreeImage -lgorilla
  LDDEPS +=
  ALL_LDFLAGS += $(LDFLAGS) -L../../Dependencies/gorilla-audio/bin/win32 -L../../Dependencies/FreeImage/lib -L../../Dependencies/GLFW/lib-vc2019 -L../../Dependencies/Freetype/lib -L/usr/lib32 -m32 -s
  LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/glad.o \
	$(OBJDIR)/b2ChainShape.o \
	$(OBJDIR)/b2CircleShape.o \
	$(OBJDIR)/b2EdgeShape.o \
	$(OBJDIR)/b2PolygonShape.o \
	$(OBJDIR)/b2BroadPhase.o \
	$(OBJDIR)/b2CollideCircle.o \
	$(OBJDIR)/b2CollideEdge.o \
	$(OBJDIR)/b2CollidePolygon.o \
	$(OBJDIR)/b2Collision.o \
	$(OBJDIR)/b2Distance.o \
	$(OBJDIR)/b2DynamicTree.o \
	$(OBJDIR)/b2TimeOfImpact.o \
	$(OBJDIR)/b2BlockAllocator.o \
	$(OBJDIR)/b2Draw.o \
	$(OBJDIR)/b2Math.o \
	$(OBJDIR)/b2Settings.o \
	$(OBJDIR)/b2StackAllocator.o \
	$(OBJDIR)/b2Timer.o \
	$(OBJDIR)/b2ChainAndCircleContact.o \
	$(OBJDIR)/b2ChainAndPolygonContact.o \
	$(OBJDIR)/b2CircleContact.o \
	$(OBJDIR)/b2Contact.o \
	$(OBJDIR)/b2ContactSolver.o \
	$(OBJDIR)/b2EdgeAndCircleContact.o \
	$(OBJDIR)/b2EdgeAndPolygonContact.o \
	$(OBJDIR)/b2PolygonAndCircleContact.o \
	$(OBJDIR)/b2PolygonContact.o \
	$(OBJDIR)/b2DistanceJoint.o \
	$(OBJDIR)/b2FrictionJoint.o \
	$(OBJDIR)/b2GearJoint.o \
	$(OBJDIR)/b2Joint.o \
	$(OBJDIR)/b2MotorJoint.o \
	$(OBJDIR)/b2MouseJoint.o \
	$(OBJDIR)/b2PrismaticJoint.o \
	$(OBJDIR)/b2PulleyJoint.o \
	$(OBJDIR)/b2RevoluteJoint.o \
	$(OBJDIR)/b2RopeJoint.o \
	$(OBJDIR)/b2WeldJoint.o \
	$(OBJDIR)/b2WheelJoint.o \
	$(OBJDIR)/b2Body.o \
	$(OBJDIR)/b2ContactManager.o \
	$(OBJDIR)/b2Fixture.o \
	$(OBJDIR)/b2Island.o \
	$(OBJDIR)/b2World.o \
	$(OBJDIR)/b2WorldCallbacks.o \
	$(OBJDIR)/b2Rope.o \
	$(OBJDIR)/distance-field.o \
	$(OBJDIR)/edtaa3func.o \
	$(OBJDIR)/font-manager.o \
	$(OBJDIR)/platform.o \
	$(OBJDIR)/texture-atlas.o \
	$(OBJDIR)/texture-font.o \
	$(OBJDIR)/utf8-utils.o \
	$(OBJDIR)/vector.o \
	$(OBJDIR)/main.o \
	$(OBJDIR)/GameObject.o \
	$(OBJDIR)/audioclip.o \
	$(OBJDIR)/audiomanager.o \
	$(OBJDIR)/batchrenderer2d.o \
	$(OBJDIR)/buffer.o \
	$(OBJDIR)/indexbuffer.o \
	$(OBJDIR)/vertexarray.o \
	$(OBJDIR)/font.o \
	$(OBJDIR)/fontmanager.o \
	$(OBJDIR)/label.o \
	$(OBJDIR)/imgui.o \
	$(OBJDIR)/imgui_demo.o \
	$(OBJDIR)/imgui_draw.o \
	$(OBJDIR)/imgui_impl_glfw.o \
	$(OBJDIR)/imgui_impl_opengl3.o \
	$(OBJDIR)/imgui_widgets.o \
	$(OBJDIR)/EngineControlLayer.o \
	$(OBJDIR)/GUILayer.o \
	$(OBJDIR)/GridLayer.o \
	$(OBJDIR)/group.o \
	$(OBJDIR)/layer.o \
	$(OBJDIR)/shader.o \
	$(OBJDIR)/sprite.o \
	$(OBJDIR)/texture.o \
	$(OBJDIR)/window.o \
	$(OBJDIR)/matrix4.o \
	$(OBJDIR)/vector2.o \
	$(OBJDIR)/vector3.o \
	$(OBJDIR)/vector4.o \
	$(OBJDIR)/PhysicsBody2D.o \
	$(OBJDIR)/PhysicsConstants.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking LETC-Core
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning LETC-Core
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/glad.o: ../../Dependencies/glad/src/glad.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2ChainShape.o: ../../L_ETC-core/ext/Box2D/Collision/Shapes/b2ChainShape.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2CircleShape.o: ../../L_ETC-core/ext/Box2D/Collision/Shapes/b2CircleShape.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2EdgeShape.o: ../../L_ETC-core/ext/Box2D/Collision/Shapes/b2EdgeShape.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2PolygonShape.o: ../../L_ETC-core/ext/Box2D/Collision/Shapes/b2PolygonShape.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2BroadPhase.o: ../../L_ETC-core/ext/Box2D/Collision/b2BroadPhase.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2CollideCircle.o: ../../L_ETC-core/ext/Box2D/Collision/b2CollideCircle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2CollideEdge.o: ../../L_ETC-core/ext/Box2D/Collision/b2CollideEdge.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2CollidePolygon.o: ../../L_ETC-core/ext/Box2D/Collision/b2CollidePolygon.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2Collision.o: ../../L_ETC-core/ext/Box2D/Collision/b2Collision.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2Distance.o: ../../L_ETC-core/ext/Box2D/Collision/b2Distance.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2DynamicTree.o: ../../L_ETC-core/ext/Box2D/Collision/b2DynamicTree.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2TimeOfImpact.o: ../../L_ETC-core/ext/Box2D/Collision/b2TimeOfImpact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2BlockAllocator.o: ../../L_ETC-core/ext/Box2D/Common/b2BlockAllocator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2Draw.o: ../../L_ETC-core/ext/Box2D/Common/b2Draw.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2Math.o: ../../L_ETC-core/ext/Box2D/Common/b2Math.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2Settings.o: ../../L_ETC-core/ext/Box2D/Common/b2Settings.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2StackAllocator.o: ../../L_ETC-core/ext/Box2D/Common/b2StackAllocator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2Timer.o: ../../L_ETC-core/ext/Box2D/Common/b2Timer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2ChainAndCircleContact.o: ../../L_ETC-core/ext/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2ChainAndPolygonContact.o: ../../L_ETC-core/ext/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2CircleContact.o: ../../L_ETC-core/ext/Box2D/Dynamics/Contacts/b2CircleContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2Contact.o: ../../L_ETC-core/ext/Box2D/Dynamics/Contacts/b2Contact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2ContactSolver.o: ../../L_ETC-core/ext/Box2D/Dynamics/Contacts/b2ContactSolver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2EdgeAndCircleContact.o: ../../L_ETC-core/ext/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2EdgeAndPolygonContact.o: ../../L_ETC-core/ext/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2PolygonAndCircleContact.o: ../../L_ETC-core/ext/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2PolygonContact.o: ../../L_ETC-core/ext/Box2D/Dynamics/Contacts/b2PolygonContact.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2DistanceJoint.o: ../../L_ETC-core/ext/Box2D/Dynamics/Joints/b2DistanceJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2FrictionJoint.o: ../../L_ETC-core/ext/Box2D/Dynamics/Joints/b2FrictionJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2GearJoint.o: ../../L_ETC-core/ext/Box2D/Dynamics/Joints/b2GearJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2Joint.o: ../../L_ETC-core/ext/Box2D/Dynamics/Joints/b2Joint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2MotorJoint.o: ../../L_ETC-core/ext/Box2D/Dynamics/Joints/b2MotorJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2MouseJoint.o: ../../L_ETC-core/ext/Box2D/Dynamics/Joints/b2MouseJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2PrismaticJoint.o: ../../L_ETC-core/ext/Box2D/Dynamics/Joints/b2PrismaticJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2PulleyJoint.o: ../../L_ETC-core/ext/Box2D/Dynamics/Joints/b2PulleyJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2RevoluteJoint.o: ../../L_ETC-core/ext/Box2D/Dynamics/Joints/b2RevoluteJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2RopeJoint.o: ../../L_ETC-core/ext/Box2D/Dynamics/Joints/b2RopeJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2WeldJoint.o: ../../L_ETC-core/ext/Box2D/Dynamics/Joints/b2WeldJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2WheelJoint.o: ../../L_ETC-core/ext/Box2D/Dynamics/Joints/b2WheelJoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2Body.o: ../../L_ETC-core/ext/Box2D/Dynamics/b2Body.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2ContactManager.o: ../../L_ETC-core/ext/Box2D/Dynamics/b2ContactManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2Fixture.o: ../../L_ETC-core/ext/Box2D/Dynamics/b2Fixture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2Island.o: ../../L_ETC-core/ext/Box2D/Dynamics/b2Island.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2World.o: ../../L_ETC-core/ext/Box2D/Dynamics/b2World.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2WorldCallbacks.o: ../../L_ETC-core/ext/Box2D/Dynamics/b2WorldCallbacks.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/b2Rope.o: ../../L_ETC-core/ext/Box2D/Rope/b2Rope.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/distance-field.o: ../../L_ETC-core/ext/freetype-gl/distance-field.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/edtaa3func.o: ../../L_ETC-core/ext/freetype-gl/edtaa3func.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/font-manager.o: ../../L_ETC-core/ext/freetype-gl/font-manager.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/platform.o: ../../L_ETC-core/ext/freetype-gl/platform.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/texture-atlas.o: ../../L_ETC-core/ext/freetype-gl/texture-atlas.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/texture-font.o: ../../L_ETC-core/ext/freetype-gl/texture-font.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utf8-utils.o: ../../L_ETC-core/ext/freetype-gl/utf8-utils.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vector.o: ../../L_ETC-core/ext/freetype-gl/vector.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main.o: ../../L_ETC-core/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GameObject.o: ../../L_ETC-core/src/GameObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/audioclip.o: ../../L_ETC-core/src/audio/audioclip.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/audiomanager.o: ../../L_ETC-core/src/audio/audiomanager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/batchrenderer2d.o: ../../L_ETC-core/src/graphics/batchrenderer2d.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/buffer.o: ../../L_ETC-core/src/graphics/buffers/buffer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/indexbuffer.o: ../../L_ETC-core/src/graphics/buffers/indexbuffer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vertexarray.o: ../../L_ETC-core/src/graphics/buffers/vertexarray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/font.o: ../../L_ETC-core/src/graphics/font/font.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/fontmanager.o: ../../L_ETC-core/src/graphics/font/fontmanager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/label.o: ../../L_ETC-core/src/graphics/font/label.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui.o: ../../L_ETC-core/src/graphics/imgui/imgui.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_demo.o: ../../L_ETC-core/src/graphics/imgui/imgui_demo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_draw.o: ../../L_ETC-core/src/graphics/imgui/imgui_draw.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_impl_glfw.o: ../../L_ETC-core/src/graphics/imgui/imgui_impl_glfw.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_impl_opengl3.o: ../../L_ETC-core/src/graphics/imgui/imgui_impl_opengl3.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_widgets.o: ../../L_ETC-core/src/graphics/imgui/imgui_widgets.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EngineControlLayer.o: ../../L_ETC-core/src/graphics/layers/EngineControlLayer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GUILayer.o: ../../L_ETC-core/src/graphics/layers/GUILayer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GridLayer.o: ../../L_ETC-core/src/graphics/layers/GridLayer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/group.o: ../../L_ETC-core/src/graphics/layers/group.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/layer.o: ../../L_ETC-core/src/graphics/layers/layer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/shader.o: ../../L_ETC-core/src/graphics/shader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sprite.o: ../../L_ETC-core/src/graphics/sprite.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/texture.o: ../../L_ETC-core/src/graphics/texture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/window.o: ../../L_ETC-core/src/graphics/window.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/matrix4.o: ../../L_ETC-core/src/math/matrix4.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vector2.o: ../../L_ETC-core/src/math/vector2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vector3.o: ../../L_ETC-core/src/math/vector3.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vector4.o: ../../L_ETC-core/src/math/vector4.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PhysicsBody2D.o: ../../L_ETC-core/src/physics/PhysicsBody2D.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PhysicsConstants.o: ../../L_ETC-core/src/physics/PhysicsConstants.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif